In [1]:
import mxnet as mx
from mxnet import gluon
from mxnet.gluon import nn
from mxnet import autograd as ag
from mxnet import ndarray as nd
from Algorithm.CNN import CNN_Model
from Algorithm.MLP import MLP
from Tools import utils
import numpy as np
import copy
import random

In [2]:
ctx = utils.try_all_gpus()
net0 = MLP()
net0.initialize(init=mx.init.Xavier(),ctx=ctx)
x = nd.random.uniform(0,255,shape=(1,28,28),ctx=ctx[0])
net0(x)
net1 = MLP()
net1.initialize(init=mx.init.Xavier(),ctx=ctx)
net1(x)
net = MLP()
net.initialize(init=mx.init.Xavier(),ctx=ctx)

In [3]:
def zero_net(net,ctx):
    net.initialize(mx.init.Xavier(),ctx=ctx)
    x = nd.random.uniform(0,255,shape=(1,28,28),ctx=ctx[0])
    net(x)
    for layer in net:
        try:
            layer.weight.data()[:] = nd.zeros(shape=layer.weight.data().shape,ctx=ctx[0])[:]
            layer.bias.data()[:] = nd.zeros(shape=layer.bias.data().shape,ctx=ctx[0])[:]
        except:
            pass
def merge(net, net_a, net_b):
    id = 0
    for layer in net:
        layer.weight.data()[:] = net_a[id].weight.data()[:] + net_b[id].weight.data()[:]
        layer.weight.data()[:] /= 2
        id += 1

In [2]:
net = MLP()
net.load_parameters("current_model.params")

In [3]:
net[0].weight.data()


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<NDArray 128x784 @cpu(0)>

In [4]:
net[2].weight.data()[0]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<NDArray 64 @cpu(0)>

In [6]:
x = 0.5
y = 4
y+=1
z = x/y
z

0.1